library(shiny)
library(bslib)
library(plotly)
library(data.table)
source("../R/datos_fuente.R")
source("../R/mod_evolucion.R")
Sys.setenv(APP_DATA_SOURCE = "local", APP_HISTORICO_PATH = "../data/historico")
serie <- cargar_serie_evolucion()
stopifnot(nrow(serie) > 0, all(serie$split_modelo %in% c("validacion", "test")))
x <- data.table(clusters_observados = c(1, 2, 3), clusters_estimados = c(1, 2, 3))
stopifnot(isTRUE(all.equal(unname(metricas_evolucion(x)), c(1, 1, 0, 0))))
x[, clusters_estimados := c(3, 4, 5)]
stopifnot(metricas_evolucion(x)["r2"] == -5, metricas_evolucion(x)["mae"] == 2)
stopifnot(is.na(metricas_evolucion(x[1])["r2"]), all(is.na(metricas_evolucion(x[0]))))
x[, clusters_observados := 2]
stopifnot(is.na(metricas_evolucion(x)["correlacion"]), is.na(metricas_evolucion(x)["r2"]))
calendario <- data.table(dia_objetivo = as.Date(c("2026-09-06", "2026-09-07", "2026-09-08")))
stopifnot(identical(filtrar_lunes_evolucion(calendario)$dia_objetivo, as.Date("2026-09-07")))
testServer(evolucion_server, args = list(serie = serie), {
  session$setInputs(periodo = range(serie$dia_objetivo))
  stopifnot(nrow(periodo()) == nrow(serie))
  invisible(output$serie)
  invisible(output$comparacion)
  session$setInputs(periodo = rep(min(serie$dia_objetivo), 2))
  stopifnot(nrow(periodo()) == 1)
  invisible(output$comparacion)
})
cat("EVOLUCION_OK\n")
